ollama:
  url: http://localhost:11434/api/
  model: phi3:mini
  embedding-model: nomic-embed-text
  vector-json-path: /home/vasara-labs/data
  options:
    max-tokens: 40
    temperature: 0.2
  timeout:
    connect-seconds: 10
