ollama:
  url: http://localhost:11434/api/
  model: phi3:mini
  embedding-model: nomic-embed-text
  vector-json-path: /home/vasara-labs/data
  options:
    max-tokens: 300
    temperature: 0.6
    top-p: 0.9
  timeout:
    connect-seconds: 10

qdrant:
  url: http://localhost:6333
  collection: ollama_documents
  vector-size: 3072
  distance: Cosine
  connection: 10
